name: Publish

on:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Publish
      - uses: cloudflare/wrangler-action@2.12.0
        with:
          node-version: 16
          cache: 'npm'
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

